### ISSUE TITLE
Default Port

### ISSUE THREAD

**Issue by MJP-76** [johnpdowling/hassio-addons#1]
Hi There

Just testing this out in my HASSIO and am sure I will be using it alot with my Finder printer so thanks for creating this addon

Just a question and I know it can be changed and will be doing so but just wondering why you settled on port 5000 as it is also AppDaemon's default port

Cheers
Matthew

**Comment by johnpdowling** [comment]
That's pretty much it. 5000 was the default and it was already what I had set my sensors to in my config yaml.
