### ISSUE TITLE
forked-daapd not work

### ISSUE THREAD

**Issue by kraineff** [johnpdowling/hassio-addons#2]
<img width="316" alt="CleanShot 2020-02-24 at 04 00 38@2x" src="https://user-images.githubusercontent.com/7906418/75121884-3ae1be00-56ba-11ea-82be-027406351278.png">
<img width="1165" alt="CleanShot 2020-02-24 at 04 00 51@2x" src="https://user-images.githubusercontent.com/7906418/75121889-4339f900-56ba-11ea-998f-f525ddbb8856.png">

HA Version: Home Assistant 0.106.0b1

**Comment by kraineff** [comment]
With new update that was 6 days ago, also not fixed!
<img width="1144" alt="CleanShot 2020-03-11 at 15 43 25@2x" src="https://user-images.githubusercontent.com/7906418/76408672-21758d00-63af-11ea-93cd-3e61bdb02841.png">

**Comment by johnpdowling** [comment]
Makes sense, the update wasn't an attempt to fix your issue. The add-on builds fine on my system (jetson nano, aarch64), could you tell me a little more about yours?

**Comment by kraineff** [comment]
Raspberry Pi 4, Docker.

**Comment by ddppddpp** [comment]
Same behavior on a RPi3B/ hassio 0.108.9

**Comment by ddppddpp** [comment]
Tested on a x86_64/Ubuntu 18.04.4 LTS with Supervised Home Assistant 109.1. Same error message.
This is a brand new install with minimal configuration changes
- DuckDNS add-on
- NGINX add-on
- http component set to use Let'sEncrypt certificates
- added repo https://github.com/johnpdowling/hassio-addons 
- pressed Install button on forked-daapd add-on
Error message:

> 20-05-01 15:52:54 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/johnpdowling/hassio-addons repository
20-05-01 15:52:55 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/a6b98bcd/fail2ban/config.json: Expecting value: line 2 column 1 (char 1)
20-05-01 15:52:55 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a6b98bcd/fail2ban/config.json from repository a6b98bcd
20-05-01 15:52:55 INFO (MainThread) [supervisor.store] Load add-ons from store: 76 all - 11 new - 0 remove
20-05-01 15:53:25 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/a6b98bcd_forked-daapd
20-05-01 15:53:25 INFO (SyncWorker_1) [supervisor.docker.addon] Start build a6b98bcd/amd64-addon-forked-daapd:0.0.2
20-05-01 15:53:30 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build a6b98bcd/amd64-addon-forked-daapd:0.0.2: The command '/bin/bash -o pipefail -c apk --no-cache add --virtual=deps1         alsa-lib-dev         autoconf         automake         cmake         avahi-dev         bash         bsd-compat-headers         build-base         confuse-dev         curl         curl-dev         ffmpeg-dev         file         git         gnutls-dev         gperf         json-c-dev         libevent-dev         libgcrypt-dev         libplist-dev         libsodium-dev         libtool         libunistring-dev         openjdk7-jre-base         protobuf-c-dev         sqlite-dev  && apk add --no-cache --virtual=deps2 --repository http://nl.alpinelinux.org/alpine/edge/testing         libantlr3c-dev         mxml-dev   && apk add --no-cache         avahi         confuse         dbus         ffmpeg         json-c         libcurl         libevent         libgcrypt         libplist         libsodium         libunistring         protobuf-c         sqlite         sqlite-libs         openssl  && apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/testing         libantlr3c         mxml   && curl -L -o /tmp/antlr-3.4-complete.jar http://www.antlr3.org/download/antlr-3.4-complete.jar &&     echo '#!/bin/bash' > /usr/local/bin/antlr3 &&     echo 'exec java -cp /tmp/antlr-3.4-complete.jar org.antlr.Tool "$@"' >> /usr/local/bin/antlr3 &&     chmod 775 /usr/local/bin/antlr3   && cd /tmp &&     git clone https://github.com/warmcat/libwebsockets.git &&     cd /tmp/libwebsockets &&     cmake ./ &&     make install   && cd /tmp &&     git clone https://github.com/ejurgensen/forked-daapd.git &&     cd /tmp/forked-daapd &&     autoreconf -fi &&     ./configure       --enable-itunes       --with-libwebsockets &&     make &&     make install   && apk del --purge deps1 deps2 &&     rm -rf /usr/local/bin/antlr3 /tmp/*' returned a non-zero code: 26

This is a disposable system so I can/I'm willing to test with any suggested options.

**Comment by ddppddpp** [comment]
I managed to build it using frenck's SSH add-on for an up-to-date primer on add-on structure. I'm not sure when I'll have the time to clean my code a do a proper PR so here's a [gist](https://gist.github.com/ddppddpp/a453fff65d53044cd0ec7cd3d0afd814) instead.

**Comment by johnpdowling** [comment]
Thanks @ddppddpp for filling in with the gist, my setup was hosed until recently so I couldn't really troubleshoot. I've updated it now to the point where it's v8.0.0 and will eventually build (looks like the errors were with openssl dependencies needing updating), however in the state that it's in now if one accesses the web ui the addon crashes. Still looking into that, pull requests welcome.

**Comment by bensuffolk** [comment]
I have just tried to install, and get the following errors:

`
20-08-21 12:37:45 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/johnpdowling/hassio-addons repository
20-08-21 12:37:48 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/a6b98bcd/fail2ban/config.json: Expecting value: line 2 column 1 (char 1)
20-08-21 12:37:48 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a6b98bcd/fail2ban/config.json from repository a6b98bcd
20-08-21 12:37:48 INFO (MainThread) [supervisor.store] Load add-ons from store: 82 all - 11 new - 0 remove
20-08-21 12:38:35 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/a6b98bcd_forked-daapd
20-08-21 12:38:35 INFO (SyncWorker_4) [supervisor.docker.addon] Start build a6b98bcd/armv7-addon-forked-daapd:0.0.2
20-08-21 12:48:57 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build a6b98bcd/armv7-addon-forked-daapd:0.0.2: The command '/bin/bash -o pipefail -c apk update  && apk add --no-cache         libcrypto1.1=1.1.1g-r0         libssl1.1=1.1.1g-r0  && apk add --no-cache --virtual deps1         alsa-lib-dev         autoconf         automake         cmake         avahi-dev         bash         bsd-compat-headers         build-base         confuse-dev         curl         curl-dev         ffmpeg-dev         file         git         gnutls-dev         gperf         json-c-dev         libevent-dev         libgcrypt-dev         libplist-dev         libsodium-dev         libtool         libunistring-dev         openjdk7-jre-base         protobuf-c-dev         sqlite-dev  && apk add --no-cache --virtual=deps2 --repository http://nl.alpinelinux.org/alpine/edge/testing         libantlr3c-dev         mxml-dev  && apk add --no-cache         avahi         confuse         dbus         ffmpeg         json-c         libcurl         libevent         libgcrypt         libplist         libsodium         libunistring         libuv=1.29.1-r0         libuv-dev=1.29.1-r0         protobuf-c         sqlite         sqlite-libs         openssl  && apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/testing         libantlr3c         mxml  && curl -L -o /tmp/antlr-3.4-complete.jar http://www.antlr3.org/download/antlr-3.4-complete.jar &&     echo '#!/bin/bash' > /usr/local/bin/antlr3 &&     echo 'exec java -cp /tmp/antlr-3.4-complete.jar org.antlr.Tool "$@"' >> /usr/local/bin/antlr3 &&     chmod 775 /usr/local/bin/antlr3  && cd /tmp &&     git clone --branch "v3.2.2" --depth=1 https://github.com/warmcat/libwebsockets.git &&     cd /tmp/libwebsockets &&     cmake ./         -DCMAKE_BUILD_TYPE=MinSizeRel         -DCMAKE_INSTALL_PREFIX=/usr         -DCMAKE_VERBOSE_MAKEFILE=TRUE         -DLWS_IPV6=ON         -DLWS_STATIC_PIC=ON         -DLWS_UNIX_SOCK=OFF         -DLWS_WITH_LIBUV=ON         -DLWS_WITH_SHARED=ON         -DLWS_WITHOUT_TESTAPPS=ON &&     make &&     make install  && cd /tmp &&     git clone https://github.com/ejurgensen/forked-daapd.git &&     cd /tmp/forked-daapd &&     autoreconf -fi &&     ./configure       --enable-itunes       --with-libwebsockets &&     make &&     make install  && apk del --purge deps1 deps2 &&     rm -rf /usr/local/bin/antlr3 /tmp/*  && cd /usr/local/etc  && sed -i -e 's/\(uid.*=.*\)/uid = "root"/g' forked-daapd.conf  && sed -i s#"ipv6 = yes"#"ipv6 = no"#g forked-daapd.conf  && sed -i s#/srv/music#/config/forked-daapd/music#g forked-daapd.conf  && sed -i s#/usr/local/var/cache/forked-daapd/songs3.db#/config/forked-daapd/cache/songs3.db#g forked-daapd.conf  && sed -i s#/usr/local/var/cache/forked-daapd/cache.db#/config/forked-daapd/cache/cache.db#g forked-daapd.conf  && sed -i s#/usr/local/var/log/forked-daapd.log#/dev/stdout#g forked-daapd.conf  && sed -i "/websocket_port\ =/ s/# *//" forked-daapd.conf  && sed -i "/trusted_networks\ =/ s/# *//" forked-daapd.conf  && sed -i "/pipe_autostart\ =/ s/# *//" forked-daapd.conf  && sed -i "/db_path\ =/ s/# *//" forked-daapd.conf  && sed -i "/cache_path\ =/ s/# *//" forked-daapd.conf' returned a non-zero code: 1
`

I'm running the HASS supervisor in docker on a raspberry pi 3B running Raspbian GNU/Linux 9 (stretch) and docker version 19.03.12. HASS version is 0.114.2 with supervisor version 235

**Comment by CMGeorge** [comment]
> I have just tried to install, and get the following errors:
> 
> I'm running the HASS supervisor in docker on a raspberry pi 3B running Raspbian GNU/Linux 9 (stretch) and docker version 19.03.12. HASS version is 0.114.2 with supervisor version 235

Same error to me, but using latest HassOS

**Comment by CMGeorge** [comment]
@bensuffolk  @johnpdowling  can you please check my modifications from here? https://github.com/CMGeorge/hassio-addons/blob/master/forked-daapd/Dockerfile

I successfully installed it.
I debugged it and found 2 build issues.
One was libssl version mismatch and other was mxml version error, which was fixed by adding the edge/community reference.

**Comment by nickw444** [comment]
Hey @CMGeorge I just tried out your modifications but still having trouble building:


```
ERROR: unsatisfiable constraints:
  libuv-1.38.1-r0:
    breaks: world[libuv=1.29.1-r0]
    satisfies: libuv-dev-1.38.1-r0[libuv=1.38.1-r0]
               cmake-3.17.2-r0[so:libuv.so.1]
  libuv-dev-1.38.1-r0:
    breaks: world[libuv-dev=1.29.1-r0]
The command '/bin/bash -o pipefail -c apk add --no-cache         avahi         confuse         dbus         ffmpeg         json-c         libcurl         libevent         libgcrypt         libplist         libsodium         libunistring         libuv=1.29.1-r0         libuv-dev=1.29.1-r0         protobuf-c         sqlite         sqlite-libs         openssl' returned a non-zero code: 4
```

**Comment by CMGeorge** [comment]
@nickw444 I removed libuv & libuv-dev version references also.
It compiled on my side with this removed. 
Can you test again?

**Comment by Just-Insane** [comment]
Is there any update on this? I'm getting the following error on install.

```
The command '/bin/bash -o pipefail -c apk update && apk add --no-cache libcrypto1.1=1.1.1g-r0 libssl1.1=1.1.1g-r0 && apk add --no-cache --virtual deps1 alsa-lib-dev autoconf automake cmake avahi-dev bash bsd-compat-headers build-base confuse-dev curl curl-dev ffmpeg-dev file git gnutls-dev gperf json-c-dev libevent-dev libgcrypt-dev libplist-dev libsodium-dev libtool libunistring-dev openjdk7-jre-base protobuf-c-dev sqlite-dev && apk add --no-cache --virtual=deps2 --repository http://nl.alpinelinux.org/alpine/edge/testing libantlr3c-dev mxml-dev && apk add --no-cache avahi confuse dbus ffmpeg json-c libcurl libevent libgcrypt libplist libsodium libunistring libuv=1.29.1-r0 libuv-dev=1.29.1-r0 protobuf-c sqlite sqlite-libs openssl && apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/testing libantlr3c mxml && curl -L -o /tmp/antlr-3.4-complete.jar http://www.antlr3.org/download/antlr-3.4-complete.jar && echo '#!/bin/bash' > /usr/local/bin/antlr3 && echo 'exec java -cp /tmp/antlr-3.4-complete.jar org.antlr.Tool "$@"' >> /usr/local/bin/antlr3 && chmod 775 /usr/local/bin/antlr3 && cd /tmp && git clone --branch "v3.2.2" --depth=1 https://github.com/warmcat/libwebsockets.git && cd /tmp/libwebsockets && cmake ./ -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=TRUE -DLWS_IPV6=ON -DLWS_STATIC_PIC=ON -DLWS_UNIX_SOCK=OFF -DLWS_WITH_LIBUV=ON -DLWS_WITH_SHARED=ON -DLWS_WITHOUT_TESTAPPS=ON && make && make install && cd /tmp && git clone https://github.com/ejurgensen/forked-daapd.git && cd /tmp/forked-daapd && autoreconf -fi && ./configure --enable-itunes --with-libwebsockets && make && make install && apk del --purge deps1 deps2 && rm -rf /usr/local/bin/antlr3 /tmp/* && cd /usr/local/etc && sed -i -e 's/\(uid.*=.*\)/uid = "root"/g' forked-daapd.conf && sed -i s#"ipv6 = yes"#"ipv6 = no"#g forked-daapd.conf && sed -i s#/srv/music#/config/forked-daapd/music#g forked-daapd.conf && sed -i s#/usr/local/var/cache/forked-daapd/songs3.db#/config/forked-daapd/cache/songs3.db#g forked-daapd.conf && sed -i s#/usr/local/var/cache/forked-daapd/cache.db#/config/forked-daapd/cache/cache.db#g forked-daapd.conf && sed -i s#/usr/local/var/log/forked-daapd.log#/dev/stdout#g forked-daapd.conf && sed -i "/websocket_port\ =/ s/# *//" forked-daapd.conf && sed -i "/trusted_networks\ =/ s/# *//" forked-daapd.conf && sed -i "/pipe_autostart\ =/ s/# *//" forked-daapd.conf && sed -i "/db_path\ =/ s/# *//" forked-daapd.conf && sed -i "/cache_path\ =/ s/# *//" forked-daapd.conf' returned a non-zero code: 8
```

There doesn't appear to be a way of building the linked dockerfile within HASS.IO.

**Comment by steuerzentrale** [comment]
> Is there any update on this? I'm getting the following error on install.
> 
> ```
> The command '/bin/bash -o pipefail -c apk update && apk add --no-cache libcrypto1.1=1.1.1g-r0 libssl1.1=1.1.1g-r0 && apk add --no-cache --virtual deps1 alsa-lib-dev autoconf automake cmake avahi-dev bash bsd-compat-headers build-base confuse-dev curl curl-dev ffmpeg-dev file git gnutls-dev gperf json-c-dev libevent-dev libgcrypt-dev libplist-dev libsodium-dev libtool libunistring-dev openjdk7-jre-base protobuf-c-dev sqlite-dev && apk add --no-cache --virtual=deps2 --repository http://nl.alpinelinux.org/alpine/edge/testing libantlr3c-dev mxml-dev && apk add --no-cache avahi confuse dbus ffmpeg json-c libcurl libevent libgcrypt libplist libsodium libunistring libuv=1.29.1-r0 libuv-dev=1.29.1-r0 protobuf-c sqlite sqlite-libs openssl && apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/testing libantlr3c mxml && curl -L -o /tmp/antlr-3.4-complete.jar http://www.antlr3.org/download/antlr-3.4-complete.jar && echo '#!/bin/bash' > /usr/local/bin/antlr3 && echo 'exec java -cp /tmp/antlr-3.4-complete.jar org.antlr.Tool "$@"' >> /usr/local/bin/antlr3 && chmod 775 /usr/local/bin/antlr3 && cd /tmp && git clone --branch "v3.2.2" --depth=1 https://github.com/warmcat/libwebsockets.git && cd /tmp/libwebsockets && cmake ./ -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=TRUE -DLWS_IPV6=ON -DLWS_STATIC_PIC=ON -DLWS_UNIX_SOCK=OFF -DLWS_WITH_LIBUV=ON -DLWS_WITH_SHARED=ON -DLWS_WITHOUT_TESTAPPS=ON && make && make install && cd /tmp && git clone https://github.com/ejurgensen/forked-daapd.git && cd /tmp/forked-daapd && autoreconf -fi && ./configure --enable-itunes --with-libwebsockets && make && make install && apk del --purge deps1 deps2 && rm -rf /usr/local/bin/antlr3 /tmp/* && cd /usr/local/etc && sed -i -e 's/\(uid.*=.*\)/uid = "root"/g' forked-daapd.conf && sed -i s#"ipv6 = yes"#"ipv6 = no"#g forked-daapd.conf && sed -i s#/srv/music#/config/forked-daapd/music#g forked-daapd.conf && sed -i s#/usr/local/var/cache/forked-daapd/songs3.db#/config/forked-daapd/cache/songs3.db#g forked-daapd.conf && sed -i s#/usr/local/var/cache/forked-daapd/cache.db#/config/forked-daapd/cache/cache.db#g forked-daapd.conf && sed -i s#/usr/local/var/log/forked-daapd.log#/dev/stdout#g forked-daapd.conf && sed -i "/websocket_port\ =/ s/# *//" forked-daapd.conf && sed -i "/trusted_networks\ =/ s/# *//" forked-daapd.conf && sed -i "/pipe_autostart\ =/ s/# *//" forked-daapd.conf && sed -i "/db_path\ =/ s/# *//" forked-daapd.conf && sed -i "/cache_path\ =/ s/# *//" forked-daapd.conf' returned a non-zero code: 8
> ```
> 
> There doesn't appear to be a way of building the linked dockerfile within HASS.IO.

Hi there

First of all thank you for this add-on. I recently wanted to install the forked-daapd too and get exactly the same error as Just-Insane. Unfortunately I dont have coding-knowledge but would be glad to help with testing.

Running Home Assistant OS 5.10 on core-2021.1.4 on a Raspi Pi 4 8GB not in a docker.


All the best

Andrew

**Comment by bubez81** [comment]
hello! Same problem here, can't understand very well if there is a workaround

**Comment by johnpdowling** [comment]
Hi, first off I hope you and yours are doing well. Second, thank you all for your patience while I was away from the project. Third, I've since migrated this project to a new OwnTone add-on + custom component/integration. So far they're working for me for seeing my AirPlay devices via OwnTone, adding + controlling their volume in OwnTone, and sending tts announcements via the UI (will soon be refactoring my node-red with the new entities for automations). Again thank you for your patience and let me know if you run into anything.
