### ISSUE TITLE
fff-api 

### ISSUE THREAD

**Issue by ronschaeffer** [johnpdowling/hassio-addons#5]
Thanks for the great add-on. Everything works as expected except that PercentageCompleted value at the /progress endpoint is always zero. For example, while a print job is running:

`http://192.168.86.111:5013/192.168.86.32/progress`

`{"BytesPrinted":"159","BytesTotal":"1000","PercentageCompleted":0}`

**Comment by johnpdowling** [comment]
I didn't write the server, just packaged it into an add-on. For what it's worth, this is how I run my sensor:

>   \- platform: rest
        name: "3D Print Job"
        resource: "http://a6b98bcd-fff-api:5000/10.x.y.z/progress"
        method: GET
        unit_of_measurement: '%'
        value_template: "{{ 100|float * value_json.BytesPrinted|float / value_json.BytesTotal|float | round(1) }}"
        force_update: true

**Comment by ronschaeffer** [comment]
Thanks for the reply. I actually have almost exactly the same sensor set up:

` - name: Flashforge Progress Percent
  platform: rest
  resource: http://192.168.86.111:5013/192.168.86.32/progress
  value_template: >
        {{ (value_json.BytesPrinted | float / value_json.BytesTotal  | float * 100) | round(1) }}
  force_update: true      
  unit_of_measurement: '%'`

I'll close the issue.
