### ISSUE TITLE
Home Assistant log errors after adding your repository

### ISSUE THREAD

**Issue by kersten-lohmeyer** [johnpdowling/hassio-addons#6]
I get log errors like this after adding your repository to my Home Assistant instance (with no add-ons installed yet):

`20-11-18 06:29:12 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/a6b98bcd/fail2ban/config.json: Expecting value: line 2 column 1 (char 1)
20-11-18 06:29:12 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/a6b98bcd/fail2ban/config.json from repository a6b98bcd`

I'm running Home Assistant 0.117.6 on Hass.os 4.16

Maybe this is something that can easily be fixed? Thank you

**Comment by johnpdowling** [comment]
Removed folder/files causing error.
